# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install tox
  - "TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}"
script: tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
deploy:
  provider: pypi
  user: darthghandi
  password:
    secure: awBTJoNR9AEMQYlG65+DpzMeE20t2HWMOfo9LwkMzVCRBo+f47BCu2n8j0TYru/nkez0jNfvo3ZMT6DGwWC4WPy/eqEIOvEhpXmFnfmCPQMK2uZa955qbqViRiHSRm2DCZSfF3YXVMMM4wSqoPGcmCszJkkCrMMCsk2z7WLECsD7hfnlImpP/maRCRH3eevfx2eoj/G5KUMufNSHAeMuXfCtLYwAcBDkdav0HAloWxLGWN9q7jDbhbodhnmPzB2qCDF8DFZ2kYymPCBVKsGpFIL2R1CBluAANhSk9rPuq9qTtS3fGPo2PW/hIBnq83Hd4CyPtO543mlB5zETAvpwgR0QVXKmx9gqImXDY0zpeCrb7YGWa3LdxRKUFs0gk9fCz94Jpr7DOSEUjV2VAf0sE151eENFdeNt5gxYSsPC3A8mJjtIWNNP1ypvTAk58fgLhag8ZclzbIbUnEZw7/5reCzkwxumnPs4xdBxyvgx5B3aaakuoNd3k1pW/QCZ759sInRW9qN01orOVeKHovyeWabSdK08jcWkImFJxWSKeaYOkDlXLC/pN1bDEkXpM4aRBPjP3timOCqoMVdrblcIk8LwO2H9Qgzh+GjJ7ebPTfngL6z7RxNmKwUQhntLt51D20OPEhqgC83dCNDRK21HZhranj0iUVv9IWXrLiqGwu4=
